'Battle Isle 2020 - Security


FUNCTION CalcSecurityAnswer&(q&, dt&, tm&)
  'Battle Isle 2020 is a trusted client which means that the server will only lazily check client data once the client has been authentificated
  'This function applies a secret algorithm on the parameters to calculate the authentification answer
END FUNCTION



FUNCTION CreateSuperSecretMissionCode$
  'Returns the map code for the super secret mission of the Kitana's Castle campaign
END FUNCTION
